name: auto_env
dependencies:
- python=3.10
- pip
- pip:
  - accuweather
  - actron-neo-api
  - adax
  - adax-local
  - adb-shell
  - adext
  - adguardhome
  - advantage-air
  - aemet-opendata
  - afsapi
  - agent-py
  - aio-geojson-generic-client
  - aio-geojson-geonetnz-quakes
  - aio-geojson-geonetnz-volcano
  - aio-geojson-nsw-rfs-incidents
  - aio-geojson-usgs-earthquakes
  - aio-georss-gdacs
  - aio-ownet
  - aioacaia
  - aioairq
  - aioairzone
  - aioairzone-cloud
  - aioamazondevices
  - aioambient
  - aioapcaccess
  - aioaquacell
  - aioaseko
  - aioasuswrt
  - aioautomower
  - aioazuredevops
  - aiobafi6
  - aiobotocore
  - aiocomelit
  - aiodhcpwatcher
  - aiodiscover
  - aiodns
  - aiodukeenergy
  - aioeafm
  - aioeagle
  - aioecowitt
  - aioelectricitymaps
  - aioemonitor
  - aioesphomeapi
  - aiofiles
  - aioflo
  - aioftp
  - aiogithubapi
  - aioguardian
  - aioharmony
  - aiohasupervisor
  - aiohomeconnect
  - aiohomekit
  - aiohttp
  - aiohttp-asyncmdnsresolver
  - aiohttp-cors
  - aiohttp-fast-zlib
  - aiohttp-sse
  - aiohue
  - aioimaplib
  - aioimmich
  - aiokafka
  - aiokef
  - aiokem
  - aiolifx
  - aiolifx-effects
  - aiolifx-themes
  - aiolookin
  - aiolyric
  - aiomealie
  - aiomodernforms
  - aiomusiccast
  - aionanoleaf
  - aionotion
  - aiontfy
  - aionut
  - aioonkyo
  - aioopenexchangerates
  - aiooui
  - aiopegelonline
  - aiopulse
  - aiopurpleair
  - aiopvapi
  - aiopvpc
  - aiopyarr
  - aioqsw
  - aioraven
  - aiorecollect
  - aioridwell
  - aioruckus
  - aiorussound
  - aioruuvigateway
  - aiosenz
  - aioshelly
  - aioskybell
  - aioslimproto
  - aiosolaredge
  - aiosomecomfort
  - aiosteamist
  - aiostreammagic
  - aioswitcher
  - aiosyncthing
  - aiotankerkoenig
  - aiotedee
  - aiotractive
  - aiounifi
  - aiousbwatcher
  - aiovlc
  - aiovodafone
  - aiowaqi
  - aiowatttime
  - aiowebdav2
  - aiowebostv
  - aiowithings
  - aioymaps
  - aiozoneinfo
  - airgradient
  - airly
  - airos
  - airthings-ble
  - airthings-cloud
  - airtouch4pyapi
  - airtouch5py
  - alpha-vantage
  - altruistclient
  - amberelectric
  - amcrest
  - androidtv
  - androidtvremote2
  - anel-pwrctrl-homeassistant
  - annotatedyaml
  - anova-wifi
  - anthemav
  - anthropic
  - anyio
  - apple-weatherkit
  - apprise
  - aprslib
  - apsystems-ez1
  - aqualogic
  - aranet4
  - arcam-fmj
  - arris-tg2492lg
  - asmog
  - astral
  - astroid
  - asusrouter
  - async-interrupt
  - async-upnp-client
  - asyncarve
  - asyncinotify
  - asyncpysupla
  - asyncsleepiq
  - asyncssh
  - atomicwrites-homeassistant
  - attrs
  - audioop-lts
  - auroranoaa
  - aurorapy
  - autarco
  - automower-ble
  - av
  - avea
  - awesomeversion
  - axis
  - ayla-iot-unofficial
  - azure-eventhub
  - azure-kusto-data
  - azure-kusto-ingest
  - azure-servicebus
  - azure-storage-blob
  - b2sdk
  - babel
  - baidu-aip
  - base36
  - batinfo
  - bcrypt
  - beautifulsoup4
  - bimmer-connected
  - bizkaibus
  - bleak
  - bleak-esphome
  - bleak-retry-connector
  - blebox-uniapi
  - blinkpy
  - blockchain
  - bluecurrent-api
  - bluemaestro-ble
  - bluetooth-adapters
  - bluetooth-auto-recovery
  - bluetooth-data-tools
  - bond-async
  - bosch-alarm-mode2
  - boschshcpy
  - boto3
  - botocore
  - bring-api
  - broadlink
  - brother
  - brottsplatskartan
  - brunt
  - bthome-ble
  - bthomehub5-devicelist
  - btsmarthub-devicelist
  - buienradar
  - cached-ipaddress
  - caldav
  - certifi
  - ciscomobilityexpress
  - ciso8601
  - clearpasspy
  - clx-sdk-xms
  - codespell
  - coinbase-advanced-py
  - colorlog
  - colorthief
  - compit-inext-api
  - concord232
  - connect-box
  - construct
  - cookidoo-api
  - coverage
  - cronsim
  - crownstone-cloud
  - crownstone-sse
  - crownstone-uart
  - cryptography
  - datadog
  - datapoint
  - dbus-fast
  - debugpy
  - decora-wifi
  - deebot-client
  - defusedxml
  - deluge-client
  - demetriek
  - denonavr
  - devialet
  - devolo-home-control-api
  - devolo-plc-api
  - dio-chacon-wifi-api
  - directv
  - discogs-client
  - discovery30303
  - doorbirdpy
  - dremel3dpy
  - dropmqttapi
  - dsmr-parser
  - dwdwfsapi
  - dynalite-devices
  - dynalite-panel
  - eagle100
  - easyenergy
  - ebusdpy
  - ecoaliface
  - eheimdigital
  - ekey-bionyxpy
  - electrickiwi-api
  - elevenlabs
  - elgato
  - eliqonline
  - elkm1-lib
  - elkoep-aio-mqtt
  - elmax-api
  - elvia
  - emoji
  - emulated-roku
  - energyflip-client
  - energyid-webhooks
  - energyzero
  - enocean
  - enturclient
  - env-canada
  - ephem
  - epicstore-api
  - epion
  - epson-projector
  - eq3btsmart
  - esphome-dashboard-api
  - essent-dynamic-pricing
  - eternalegypt
  - eufylife-ble-client
  - evohome-async
  - evolutionhttp
  - faadelays
  - fastdotcom
  - feedparser
  - file-read-backwards
  - fing-agent-api
  - fints
  - fitbit
  - fitbit-web-api
  - fivem-api
  - fixerio
  - fjaraskupan
  - flexit-bacnet
  - flipr-api
  - flux-led
  - fnv-hash-fast
  - foobot-async
  - forecast-solar
  - fortiosapi
  - freebox-api
  - freesms
  - freezegun
  - fritzconnection
  - fyta-cli
  - gardena-bluetooth
  - gassist-text
  - gcal-sync
  - genie-partner-sdk
  - geniushub-client
  - geocachingapi
  - geopy
  - georss-generic-client
  - georss-ign-sismologia-client
  - georss-qld-bushfire-alert-client
  - getmac
  - gios
  - gitterpy
  - glances-api
  - go2rtc-client
  - goalzero
  - goodwe
  - google-air-quality-api
  - google-api-python-client
  - google-cloud-pubsub
  - google-cloud-speech
  - google-cloud-texttospeech
  - google-genai
  - google-maps-routing
  - google-nest-sdm
  - google-photos-library-api
  - goslide-api
  - gotailwind
  - govee-ble
  - govee-local-api
  - gpiozero
  - gps3
  - greeclimate
  - greeneye-monitor
  - greenwavereality
  - gridnet
  - growattserver
  - gspread
  - gtts
  - guppy3
  - h2
  - ha-ffmpeg
  - ha-iotawattpy
  - ha-philipsjs
  - ha-silabs-firmware-client
  - habiticalib
  - habluetooth
  - hanna-cloud
  - hap-python
  - hass-nabucasa
  - hass-splunk
  - hassil
  - hatasmota
  - hdate
  - heatmiserv3
  - here-routing
  - here-transit
  - hikvision
  - hkavr
  - hko
  - hlk-sw16
  - hole
  - holidays
  - home-assistant-bluetooth
  - home-assistant-frontend
  - home-assistant-intents
  - homematicip
  - horimote
  - httplib2
  - httpx
  - huawei-lte-api
  - hueble
  - huum
  - hyperion-py
  - iammeter
  - iaqualink
  - ibeacon-ble
  - ical
  - icalendar
  - icmplib
  - idasen-ha
  - ifaddr
  - iglo
  - igloohome-api
  - ihcsdk
  - imeon-inverter-api
  - imgw-pib
  - incomfort-client
  - influxdb
  - influxdb-client
  - inkbird-ble
  - insteon-frontend-home-assistant
  - intellifire4py
  - iometer
  - iottycloud
  - iperf3
  - irm-kmi-api
  - isal
  - ismartgate
  - israel-rail-api
  - jaraco-abode
  - jellyfin-apiclient-python
  - jinja2
  - jsonpath
  - justnimbus
  - kaiterra-async-client
  - keba-kecontact
  - kegtron-ble
  - kiwiki-client
  - knocki
  - knx-frontend
  - konnected
  - krakenex
  - lacrosse-view
  - lakeside
  - laundrify-aio
  - lcn-frontend
  - ld2410-ble
  - leaone-ble
  - led-ble
  - lektricowifi
  - letpot
  - libpyfoscamcgi
  - libpyvivotek
  - librehardwaremonitor-api
  - librouteros
  - librt
  - libsoundtouch
  - license-expression
  - lightify
  - lightwave
  - limitlessled
  - livisi
  - locationsharinglib
  - london-tube-status
  - loqedapi
  - lru-dict
  - luftdaten
  - lunatone-rest-api-client
  - lupupy
  - lw12
  - lxml
  - mastodon-py
  - matrix-nio
  - maxcube-api
  - mbddns
  - mcp
  - mcstatus
  - meater-python
  - medcom-ble
  - melnor-bluetooth
  - messagebird
  - meteo-lt-pkg
  - meteoalertapi
  - meteofrance-api
  - mficlient
  - micloud
  - microbeespy
  - mill-local
  - millheater
  - minio
  - moat-ble
  - mock-open
  - moehlenhoff-alpha2
  - momonga
  - monzopy
  - mopeka-iot-ble
  - motionblinds
  - motionblindsble
  - motioneye-client
  - mozart-api
  - mullvad-api
  - music-assistant-client
  - mutagen
  - mutesync
  - mvg
  - mypermobil
  - mypy-dev
  - myuplink
  - nad-receiver
  - ndms2-client
  - nessclient
  - netdata
  - netmap
  - nettigo-air-monitor
  - neurio
  - nexia
  - nextcloudmonitor
  - nextcord
  - nextdns
  - nhc
  - nibe
  - nice-go
  - niluclient
  - noaa-coops
  - notifications-android-tv
  - notify-events
  - nsapi
  - nsw-fuel-api-client
  - nuheat
  - numato-gpio
  - numpy
  - nyt-games
  - oasatelematics
  - oauth2client
  - objgraph
  - odp-amsterdam
  - oemthermostat
  - ohme
  - ollama
  - omnilogic
  - ondilo
  - onedrive-personal-sdk
  - onvif-zeep-async
  - open-garage
  - open-meteo
  - openai
  - openerz-api
  - openevsewifi
  - openhomedevice
  - openrgb-python
  - opensensemap-api
  - openwebifpy
  - openwrt-luci-rpc
  - openwrt-ubus-rpc
  - opower
  - oralb-ble
  - orjson
  - oru
  - orvibo
  - ourgroceries
  - ovoenergy
  - p1monitor
  - packaging
  - paho-mqtt
  - panacotta
  - panasonic-viera
  - pdunehd
  - peblar
  - peco
  - pencompy
  - pescea
  - pexpect
  - phone-modem
  - pigpio
  - pilight
  - pillow
  - pipdeptree
  - plexapi
  - plexauth
  - plexwebsocket
  - plugwise
  - pmsensor
  - poolsense
  - powerfox
  - praw
  - prayer-times-calculator-offline
  - pre-commit
  - progettihwsw
  - proliphix
  - prometheus-client
  - propcache
  - prowlpy
  - proxmoxer
  - psnawp
  - psutil
  - psutil-home-assistant
  - pulsectl
  - pushbullet-py
  - pushover-complete
  - pvo
  - py-aosmith
  - py-canary
  - py-ccm15
  - py-cpuinfo
  - py-dactyl
  - py-dormakaba-dkey
  - py-improv-ble-client
  - py-madvr2
  - py-melissa-climate
  - py-nextbusnext
  - py-nightscout
  - py-schluter
  - py-sucks
  - py-synologydsm-api
  - pyads
  - pyaehw4a1
  - pyaftership
  - pyairnow
  - pyairobotrest
  - pyairvisual
  - pyanglianwater
  - pyaprilaire
  - pyatag
  - pyatmo
  - pyatome
  - pyatv
  - pyaussiebb
  - pybalboa
  - pybbox
  - pyblackbird
  - pyblu
  - pybotvac
  - pybravia
  - pycarwings2
  - pycec
  - pycfdns
  - pychannels
  - pychromecast
  - pycketcasts
  - pycmus
  - pycomfoconnect
  - pycontrol4
  - pycoolmasternet-async
  - pycountry
  - pycsspeechtts
  - pycync
  - pydaikin
  - pydanfossair
  - pydantic
  - pydeako
  - pydeconz
  - pydelijn
  - pydexcom
  - pydiscovergy
  - pydoods
  - pydrawise
  - pydroid-ipcam
  - pydroplet
  - pyduotecno
  - pyebox
  - pyecoforest
  - pyeconet
  - pyecotrend-ista
  - pyedimax
  - pyefergy
  - pyegps
  - pyelectra
  - pyemby
  - pyemoncms
  - pyenphase
  - pyenvisalink
  - pyephember2
  - pyeverlights
  - pyevilgenius
  - pyezvizapi
  - pyfibaro
  - pyfido
  - pyfirefly
  - pyfireservicerota
  - pyflic
  - pyflume
  - pyfnip
  - pyforked-daapd
  - pyfreedompro
  - pyfritzhome
  - pyfronius
  - pyfttt
  - pygatt
  - pygtfs
  - pygti
  - pyhaversion
  - pyheos
  - pyhik
  - pyhive-integration
  - pyhomee
  - pyhomematic
  - pyhomeworks
  - pyialarm
  - pyicloud
  - pyinsteon
  - pyintesishome
  - pyipma
  - pyipp
  - pyiqvia
  - pyirishrail
  - pyiskra
  - pyiss
  - pyisy
  - pyitachip2ir
  - pyituran
  - pyjvcprojector
  - pyjwt
  - pykaleidescape
  - pykira
  - pykmtronic
  - pykodi
  - pykoplenti
  - pykrakenapi
  - pykulersky
  - pykwb
  - pylacrosse
  - pylamarzocco
  - pylast
  - pylaunches
  - pylgnetcast
  - pylibrespot-java
  - pylint
  - pylint-per-file-ignores
  - pylitejet
  - pylitterbot
  - pyloadapi
  - pylutron
  - pylutron-caseta
  - pymailgunner
  - pymata-express
  - pymediaroom
  - pymeteireann
  - pymeteoclimatic
  - pymetno
  - pymicro-vad
  - pymicrobot
  - pymiele
  - pymitv
  - pymochad
  - pymodbus
  - pymonoprice
  - pymsteams
  - pymysensors
  - pynacl
  - pynecil
  - pynetgear
  - pynetio
  - pynina
  - pynintendoparental
  - pynobo
  - pynordpool
  - pynuki
  - pynws
  - pynx584
  - pynzbgetapi
  - pyobihai
  - pyoctoprintapi
  - pyombi
  - pyopenssl
  - pyopenuv
  - pyopenweathermap
  - pyopnsense
  - pyoppleio-legacy
  - pyosoenergyapi
  - pyotgw
  - pyotp
  - pyoverkiz
  - pypalazzetti
  - pypaperless
  - pypca
  - pypck
  - pypglab
  - pypjlink2
  - pyplaato
  - pypoint
  - pyportainer
  - pyprobeplus
  - pyprof2calltree
  - pyprosegur
  - pyprusalink
  - pyps4-2ndscreen
  - pyqrcode
  - pyqvrpro
  - pyqwikswitch
  - pyrail
  - pyrainbird
  - pyrate-limiter
  - pyrecswitch
  - pyrepetierng
  - pyrfxtrx
  - pyrisco
  - pyrituals
  - pyrmvtransport
  - pyroute2
  - pyrympro
  - pysabnzbd
  - pysaj
  - pysaunum
  - pyschlage
  - pysdcp
  - pysensibo
  - pyserial
  - pyserial-asyncio-fast
  - pysesame2
  - pyseventeentrack
  - pysiaalarm
  - pysignalclirestapi
  - pyskyqhub
  - pysma
  - pysmappee
  - pysmarlaapi
  - pysmartthings
  - pysmarty2
  - pysmhi
  - pysml
  - pysmlight
  - pysnmp
  - pysnooz
  - pysoma
  - pyspcwebgw
  - pyspeex-noise
  - pysqueezebox
  - pysrdaligateway
  - pystiebeleltron
  - pysuezv2
  - pyswitchbee
  - pyswitchbot
  - pyswitchmate
  - pysyncthru
  - pytautulli
  - pytest
  - pytest-aiohttp
  - pytest-asyncio
  - pytest-cov
  - pytest-freezer
  - pytest-github-actions-annotate-failures
  - pytest-picked
  - pytest-socket
  - pytest-sugar
  - pytest-timeout
  - pytest-unordered
  - pytest-xdist
  - pythinkingcleaner
  - python-awair
  - python-blockchain-api
  - python-bsblan
  - python-citybikes
  - python-clementine-remote
  - python-digitalocean
  - python-ecobee-api
  - python-etherscan-api
  - python-family-hub-local
  - python-fullykiosk
  - python-gc100
  - python-gitlab
  - python-google-drive-api
  - python-google-weather-api
  - python-homeassistant-analytics
  - python-homewizard-energy
  - python-hpilo
  - python-izone
  - python-join-api
  - python-kasa
  - python-linkplay
  - python-matter-server
  - python-melcloud
  - python-miio
  - python-motionmount
  - python-mpd2
  - python-mystrom
  - python-open-router
  - python-opendata-transport
  - python-opensky
  - python-otbr-api
  - python-overseerr
  - python-picnic-api2
  - python-pooldose
  - python-rabbitair
  - python-ripple-api
  - python-roborock
  - python-slugify
  - python-smarttub
  - python-snoo
  - python-songpal
  - python-tado
  - python-technove
  - python-telegram-bot
  - python-vlc
  - python-xbox
  - pythonegardia
  - pythonkuma
  - pytibber
  - pytile
  - pytomorrowio
  - pytouchline-extended
  - pytouchlinesl
  - pytraccar
  - pytradfri
  - pytrafikverket
  - pytransportnsw
  - pytrydan
  - pyturbojpeg
  - pyuptimerobot
  - pyvera
  - pyversasense
  - pyvesync
  - pyvicare
  - pyvizio
  - pyvlx
  - pyvolumio
  - pyw215
  - pyw800rf32
  - pywaze
  - pyweatherflowudp
  - pywebpush
  - pywemo
  - pywilight
  - pywizlight
  - pywmspro
  - pyws66i
  - pyxeoma
  - pyxiaomigateway
  - pyyaml
  - pyyardian
  - pyzbar
  - pyzerproc
  - qbittorrent-api
  - qbusmqttapi
  - qingping-ble
  - qnapstats
  - quantum-gateway
  - rachiopy
  - radios
  - radiotherm
  - raincloudy
  - rapt-ble
  - raspyrfm-client
  - refoss-ha
  - regenmaschine
  - renault-api
  - renson-endura-delta
  - reolink-aio
  - requests
  - requests-mock
  - respx
  - restrictedpython
  - rfk101py
  - rflink
  - ring-doorbell
  - ritassist
  - rjpl
  - rocketchat-api
  - rokuecp
  - romy
  - roombapy
  - roonapi
  - rova
  - rpi-bad-power
  - rtmapi
  - ruff
  - russound
  - ruuvitag-ble
  - rxv
  - samsungctl
  - samsungtvws
  - sanix
  - satel-integra
  - screenlogicpy
  - scsgate
  - securetar
  - sendgrid
  - sense-energy
  - sensirion-ble
  - sensorpro-ble
  - sensorpush-api
  - sensorpush-ble
  - sensorpush-ha
  - sensoterra
  - sentence-stream
  - sentry-sdk
  - sfrbox-api
  - sharkiq
  - sharp-aquos-rc
  - shodan
  - simplefin4py
  - simplehound
  - simplepush
  - simplisafe-python
  - sisyphus-control
  - skyboxremote
  - slack-sdk
  - slixmpp
  - smart-meter-texas
  - snapcast
  - soco
  - solaredge-local
  - solaredge-web
  - solarlog-cli
  - solax
  - somfy-mylink-synergy
  - sonos-websocket
  - speak2mary
  - speedtest-cli
  - spotifyaio
  - sqlalchemy
  - sqlparse
  - srpenergy
  - standard-aifc
  - standard-telnetlib
  - starline
  - starlingbank
  - starlink-grpc-core
  - statsd
  - steamodd
  - stookwijzer
  - streamlabswater
  - subarulink
  - surepy
  - swisshydrodata
  - switchbot-api
  - synology-srm
  - syrupy
  - systembridgeconnector
  - tailscale
  - tami4edgeapi
  - tank-utility
  - tapsaff
  - tellcore-net
  - tellcore-py
  - tellduslive
  - temescal
  - temperusb
  - tesla-fleet-api
  - tesla-powerwall
  - tesla-wall-connector
  - teslemetry-stream
  - tessie-api
  - thermobeacon-ble
  - thermopro-ble
  - thingspeak
  - thinqconnect
  - tikteck
  - tilt-ble
  - tilt-pi
  - tmb
  - todoist-api-python
  - togrill-bluetooth
  - tololib
  - toonapi
  - total-connect-client
  - tp-connected
  - tplink-omada-client
  - tqdm
  - transmission-rpc
  - travispy
  - triggercmd
  - ttls
  - ttn-client
  - tuya-device-sharing-sdk
  - twentemilieu
  - twilio
  - twitchapi
  - twitterapi
  - typedmonarchmoney
  - types-aiofiles
  - types-atomicwrites
  - types-caldav
  - types-chardet
  - types-croniter
  - types-decorator
  - types-pexpect
  - types-protobuf
  - types-psutil
  - types-pyserial
  - types-python-dateutil
  - types-python-slugify
  - types-pytz
  - types-pyyaml
  - types-requests
  - types-xmltodict
  - typing-extensions
  - uasiren
  - uiprotect
  - ulid-transform
  - ultraheat-api
  - unifi-ap
  - unifi-discovery
  - unifiled
  - universal-silabs-flasher
  - upb-lib
  - upcloud-api
  - url-normalize
  - urllib3
  - uv
  - uvcclient
  - vacuum-map-parser-roborock
  - vallox-websocket-api
  - vegehub
  - vehicle
  - velbus-aio
  - venstarcolortouch
  - victron-ble-ha-parser
  - victron-vrm
  - vilfo-api-client
  - vobject
  - voip-utils
  - volkszaehler
  - voluptuous
  - voluptuous-openapi
  - voluptuous-serialize
  - volvocarsapi
  - vsure
  - vtjp
  - wakeonlan
  - wallbox
  - watchdog
  - waterfurnace
  - watergate-local-api
  - weatherflow4py
  - webexpythonsdk
  - webio-api
  - webmin-xmlrpc
  - webrtc-models
  - weheat
  - whirlpool-sixth-sense
  - whois
  - wiffi
  - wirelesstagpy
  - wled
  - wolf-comm
  - wsdiscovery
  - wsdot
  - wyoming
  - xiaomi-ble
  - xknx
  - xknxproject
  - xmltodict
  - xs1-api-client
  - yalesmartalarmclient
  - yalexs
  - yalexs-ble
  - yamllint
  - yarl
  - yeelight
  - yeelightsunflower
  - yolink-api
  - youless-api
  - youtubeaio
  - yt-dlp
  - zabbix-utils
  - zamg
  - zcc-helper
  - zeroconf
  - zeversolar
  - zha
  - zhong-hong-hvac
  - ziggo-mediabox-xl
  - zm-py
  - zwave-js-server-python
  - zwave-me-ws
